### ISSUE TITLE
[BUG] Starboard count decreases by one with double reaction

### ISSUE THREAD

**Issue by Endercheif** [Sigmanificient/mCodingBot#30]
#### Precursor Information:
In **_#memes_** a message has 10 stars (none by author)
This meme makes it on **_#starboard_** with one reaction and the message says "10 stars".
One of those 10 stars was from me.
If I react with a star in **_#starboard_**, the star count remains the same.
So far everything in normal.
#### The Issue: 
Unreacting in **_#starboard_**, changes the count to 9 even though the message in **_#memes_** has 10 stars.
#### Additional Information:
If I unreact in **_#memes_* and then react again in **_#memes_*, the problem is "fixed" as the count won't decrease, just increase when rereacting.

**Comment by CircuitSacul** [comment]
This is intentional. It's a performance choice I made, and this is how it's done on my public bot too. It's rather complex to support stars attached to starboard messages, especially here, since the "Starboard message" is just an id attached to the original "Message".

**Comment by Endercheif** [comment]
Got it. Closing this then
